default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: http-api_dev

test:
  <<: *default
  database: http-api_test

production:
  <<: *default
  database: http-api_production
